 import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';

@Injectable()
export class RestProvider {

  randomUrl = 'https://randomuser.me/api/?results=25';

    page: string;
  constructor(
    public http: HttpClient,
    private afAuth: AngularFireAuth) {
    console.log('RestProvider Cargado');
  }

  getUsersRandom() {
      return this.http.get(this.randomUrl);
  }

  loginFB(email:string, password:string) {
      return this.afAuth.auth.signInWithEmailAndPassword(email, password)
        .then(user=>Promise.resolve(user))
        .catch(err=>Promise.reject(err))
  }
  catch(e){
    console.log(e);
  }
  initProducts() {
    var products = [
  {
    "id": 1282,
    "nombre": "Silla",
    "descripcion": "Es una Silla de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "28 x 26",
    "precio": 17,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 3,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 34,
    "stock": 0,
    "disponible": 1,
    "votosup": 68,
    "votosdown": 25
  },
  {
    "id": 1417,
    "nombre": "Cama",
    "descripcion": "Es una Cama de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "17 x 22",
    "precio": 34,
    "imagen": "https://dasdb9h4gaafx.cloudfront.net/788879/630/e4a8d78be453c9882204ab810d7f1a24.jpg",
    "descuento": 0,
    "categoria": 10,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 16,
    "stock": 5,
    "disponible": 0,
    "votosup": 15,
    "votosdown": 53
  },
  {
    "id": 2328,
    "nombre": "Mordedor",
    "descripcion": "Es una Mordedor de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "26 x 21",
    "precio": 31,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 0,
    "categoria": 4,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 42,
    "stock": 11,
    "disponible": 1,
    "votosup": 80,
    "votosdown": 24
  },
  {
    "id": 2029,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "26 x 25",
    "precio": 50,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 1,
    "categoria": 10,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 53,
    "stock": 11,
    "disponible": 1,
    "votosup": 24,
    "votosdown": 94
  },
  {
    "id": 1366,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "16 x 22",
    "precio": 24,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 1,
    "categoria": 2,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 57,
    "stock": 8,
    "disponible": 1,
    "votosup": 41,
    "votosdown": 26
  },
  {
    "id": 1315,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "20 x 25",
    "precio": 3,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Salud_Higiene_I_19470_h.jpg",
    "descuento": 0,
    "categoria": 3,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 57,
    "stock": 3,
    "disponible": 1,
    "votosup": 96,
    "votosdown": 96
  },
  {
    "id": 1999,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "26 x 40",
    "precio": 34,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 1,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 32,
    "stock": 4,
    "disponible": 1,
    "votosup": 59,
    "votosdown": 25
  },
  {
    "id": 2576,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "30 x 24",
    "precio": 50,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 0,
    "categoria": 5,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 61,
    "stock": 8,
    "disponible": 1,
    "votosup": 95,
    "votosdown": 16
  },
  {
    "id": 1898,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "30 x 38",
    "precio": 17,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 1,
    "categoria": 1,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 67,
    "stock": 2,
    "disponible": 1,
    "votosup": 25,
    "votosdown": 79
  },
  {
    "id": 1496,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "17 x 33",
    "precio": 28,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 0,
    "categoria": 10,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 38,
    "stock": 9,
    "disponible": 0,
    "votosup": 35,
    "votosdown": 43
  },
  {
    "id": 1241,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color rojo y de la talla L",
    "color": "rojo",
    "talla": "L",
    "medidas": "23 x 17",
    "precio": 40,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Caseta_I_39530_h.jpg",
    "descuento": 0,
    "categoria": 7,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 32,
    "stock": 3,
    "disponible": 1,
    "votosup": 18,
    "votosdown": 3
  },
  {
    "id": 2002,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "18 x 38",
    "precio": 35,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 5,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 10,
    "stock": 11,
    "disponible": 1,
    "votosup": 16,
    "votosdown": 96
  },
  {
    "id": 2993,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "23 x 39",
    "precio": 16,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/53AD/8090/6AEC/1A19/F496/C0A8/2BB8/D81E/31862_Perro_Pollo.jpg",
    "descuento": 0,
    "categoria": 6,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 48,
    "stock": 3,
    "disponible": 1,
    "votosup": 59,
    "votosdown": 89
  },
  {
    "id": 2202,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color naranja y de la talla L",
    "color": "naranja",
    "talla": "L",
    "medidas": "30 x 37",
    "precio": 7,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 40,
    "stock": 0,
    "disponible": 1,
    "votosup": 38,
    "votosdown": 30
  },
  {
    "id": 2360,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "29 x 37",
    "precio": 50,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 6,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 35,
    "stock": 15,
    "disponible": 0,
    "votosup": 47,
    "votosdown": 93
  },
  {
    "id": 2244,
    "nombre": "Volador",
    "descripcion": "Es una Volador de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "26 x 38",
    "precio": 15,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 6,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 44,
    "stock": 11,
    "disponible": 1,
    "votosup": 98,
    "votosdown": 39
  },
  {
    "id": 1275,
    "nombre": "TV",
    "descripcion": "Es una TV de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "16 x 32",
    "precio": 7,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 7,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 60,
    "stock": 8,
    "disponible": 0,
    "votosup": 82,
    "votosdown": 33
  },
  {
    "id": 2450,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "18 x 25",
    "precio": 1,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 5,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 51,
    "stock": 4,
    "disponible": 0,
    "votosup": 24,
    "votosdown": 96
  },
  {
    "id": 2607,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla L",
    "color": "azul",
    "talla": "L",
    "medidas": "27 x 34",
    "precio": 20,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 9,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 27,
    "stock": 0,
    "disponible": 1,
    "votosup": 25,
    "votosdown": 30
  },
  {
    "id": 2577,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla S",
    "color": "rojo",
    "talla": "S",
    "medidas": "24 x 16",
    "precio": 10,
    "imagen": "https://dasdb9h4gaafx.cloudfront.net/788879/630/e4a8d78be453c9882204ab810d7f1a24.jpg",
    "descuento": 1,
    "categoria": 7,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 18,
    "stock": 15,
    "disponible": 0,
    "votosup": 47,
    "votosdown": 58
  },
  {
    "id": 1952,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "30 x 19",
    "precio": 3,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/53AD/8090/6AEC/1A19/F496/C0A8/2BB8/D81E/31862_Perro_Pollo.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 27,
    "stock": 1,
    "disponible": 0,
    "votosup": 48,
    "votosdown": 75
  },
  {
    "id": 1801,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "25 x 19",
    "precio": 48,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Salud_Higiene_I_19470_h.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 14,
    "stock": 9,
    "disponible": 0,
    "votosup": 83,
    "votosdown": 35
  },
  {
    "id": 2994,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "28 x 18",
    "precio": 17,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 1,
    "categoria": 10,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 34,
    "stock": 6,
    "disponible": 0,
    "votosup": 88,
    "votosdown": 89
  },
  {
    "id": 2209,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "25 x 38",
    "precio": 26,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Cama_I_2807_h.jpg",
    "descuento": 1,
    "categoria": 1,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 59,
    "stock": 3,
    "disponible": 1,
    "votosup": 48,
    "votosdown": 62
  },
  {
    "id": 2824,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "21 x 31",
    "precio": 43,
    "imagen": "https://dasdb9h4gaafx.cloudfront.net/788879/630/e4a8d78be453c9882204ab810d7f1a24.jpg",
    "descuento": 0,
    "categoria": 1,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 54,
    "stock": 0,
    "disponible": 1,
    "votosup": 47,
    "votosdown": 84
  },
  {
    "id": 1324,
    "nombre": "Silla",
    "descripcion": "Es una Silla de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "27 x 27",
    "precio": 49,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 10,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 47,
    "stock": 8,
    "disponible": 0,
    "votosup": 8,
    "votosdown": 47
  },
  {
    "id": 1017,
    "nombre": "Cama",
    "descripcion": "Es una Cama de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "30 x 36",
    "precio": 12,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 1,
    "categoria": 9,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 39,
    "stock": 0,
    "disponible": 1,
    "votosup": 21,
    "votosdown": 13
  },
  {
    "id": 2965,
    "nombre": "Mordedor",
    "descripcion": "Es una Mordedor de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "24 x 39",
    "precio": 15,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Salud_Higiene_I_19470_h.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 47,
    "stock": 7,
    "disponible": 0,
    "votosup": 41,
    "votosdown": 54
  },
  {
    "id": 1060,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla M",
    "color": "amarillo",
    "talla": "M",
    "medidas": "30 x 27",
    "precio": 37,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 1,
    "categoria": 9,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 44,
    "stock": 9,
    "disponible": 0,
    "votosup": 37,
    "votosdown": 41
  },
  {
    "id": 2927,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla L",
    "color": "azul",
    "talla": "L",
    "medidas": "22 x 18",
    "precio": 36,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/527B/E2C2/4E0A/7C97/454F/C0A8/28BE/4A44/Trixie_Perro_Coche_I_1290_h.jpg",
    "descuento": 0,
    "categoria": 10,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 48,
    "stock": 9,
    "disponible": 0,
    "votosup": 84,
    "votosdown": 77
  },
  {
    "id": 1983,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "18 x 27",
    "precio": 6,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9h18nGTXd7WKIvMNqCcCKSWFBrfcsm1x76XtncSKiQmB_UAiG",
    "descuento": 0,
    "categoria": 1,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 16,
    "stock": 1,
    "disponible": 0,
    "votosup": 99,
    "votosdown": 69
  },
  {
    "id": 2455,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "27 x 33",
    "precio": 47,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Salud_Higiene_I_19470_h.jpg",
    "descuento": 0,
    "categoria": 4,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 19,
    "stock": 12,
    "disponible": 1,
    "votosup": 33,
    "votosdown": 6
  },
  {
    "id": 2340,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color rojo y de la talla XS",
    "color": "rojo",
    "talla": "XS",
    "medidas": "19 x 38",
    "precio": 7,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 3,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 57,
    "stock": 8,
    "disponible": 1,
    "votosup": 85,
    "votosdown": 13
  },
  {
    "id": 2138,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "16 x 15",
    "precio": 18,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/527B/E2C2/4E0A/7C97/454F/C0A8/28BE/4A44/Trixie_Perro_Coche_I_1290_h.jpg",
    "descuento": 0,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 64,
    "stock": 3,
    "disponible": 1,
    "votosup": 68,
    "votosdown": 33
  },
  {
    "id": 2495,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla M",
    "color": "amarillo",
    "talla": "M",
    "medidas": "24 x 33",
    "precio": 23,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 1,
    "categoria": 3,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 38,
    "stock": 7,
    "disponible": 0,
    "votosup": 19,
    "votosdown": 39
  },
  {
    "id": 1251,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color naranja y de la talla L",
    "color": "naranja",
    "talla": "L",
    "medidas": "17 x 39",
    "precio": 29,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 44,
    "stock": 13,
    "disponible": 0,
    "votosup": 55,
    "votosdown": 40
  },
  {
    "id": 2301,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "15 x 33",
    "precio": 42,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 0,
    "categoria": 9,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 13,
    "stock": 3,
    "disponible": 1,
    "votosup": 65,
    "votosdown": 36
  },
  {
    "id": 1452,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "27 x 32",
    "precio": 5,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 0,
    "categoria": 10,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 19,
    "stock": 6,
    "disponible": 1,
    "votosup": 26,
    "votosdown": 98
  },
  {
    "id": 1610,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "26 x 19",
    "precio": 40,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 69,
    "stock": 13,
    "disponible": 1,
    "votosup": 4,
    "votosdown": 84
  },
  {
    "id": 2825,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "25 x 23",
    "precio": 33,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Caseta_I_39530_h.jpg",
    "descuento": 0,
    "categoria": 4,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 57,
    "stock": 8,
    "disponible": 1,
    "votosup": 52,
    "votosdown": 98
  },
  {
    "id": 1590,
    "nombre": "Volador",
    "descripcion": "Es una Volador de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "30 x 17",
    "precio": 41,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 59,
    "stock": 13,
    "disponible": 0,
    "votosup": 31,
    "votosdown": 88
  },
  {
    "id": 1542,
    "nombre": "TV",
    "descripcion": "Es una TV de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "28 x 36",
    "precio": 11,
    "imagen": "https://d2rp9bqx0m7ihv.cloudfront.net/media/1/photos/products/015699/rejilla-ventilacion-para-coches-trixie-perro-coche-1310-h_1_g.jpg",
    "descuento": 0,
    "categoria": 9,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 37,
    "stock": 15,
    "disponible": 0,
    "votosup": 80,
    "votosdown": 13
  },
  {
    "id": 1216,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "19 x 20",
    "precio": 47,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 0,
    "categoria": 8,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 53,
    "stock": 6,
    "disponible": 0,
    "votosup": 24,
    "votosdown": 1
  },
  {
    "id": 1737,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "19 x 27",
    "precio": 31,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 33,
    "stock": 3,
    "disponible": 1,
    "votosup": 55,
    "votosdown": 70
  },
  {
    "id": 2252,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "21 x 20",
    "precio": 14,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 1,
    "categoria": 5,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 35,
    "stock": 7,
    "disponible": 0,
    "votosup": 49,
    "votosdown": 39
  },
  {
    "id": 2887,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "29 x 37",
    "precio": 30,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 30,
    "stock": 6,
    "disponible": 1,
    "votosup": 74,
    "votosdown": 34
  },
  {
    "id": 1849,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "30 x 32",
    "precio": 33,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Cama_I_2807_h.jpg",
    "descuento": 1,
    "categoria": 5,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 54,
    "stock": 7,
    "disponible": 1,
    "votosup": 100,
    "votosdown": 6
  },
  {
    "id": 2200,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "25 x 40",
    "precio": 50,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Cama_I_2807_h.jpg",
    "descuento": 0,
    "categoria": 6,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 44,
    "stock": 9,
    "disponible": 1,
    "votosup": 67,
    "votosdown": 74
  },
  {
    "id": 1494,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "26 x 23",
    "precio": 34,
    "imagen": "http://www.saloncaninoguau.com/wp-content/uploads/2017/02/Trixie_Perro_Viaje_2489_h-300x300.jpg",
    "descuento": 1,
    "categoria": 3,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 36,
    "stock": 14,
    "disponible": 1,
    "votosup": 95,
    "votosdown": 78
  },
  {
    "id": 1153,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "29 x 33",
    "precio": 46,
    "imagen": "http://www.saloncaninoguau.com/wp-content/uploads/2017/02/Trixie_Perro_Viaje_2489_h-300x300.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 16,
    "stock": 14,
    "disponible": 0,
    "votosup": 52,
    "votosdown": 87
  },
  {
    "id": 1998,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla M",
    "color": "rojo",
    "talla": "M",
    "medidas": "16 x 35",
    "precio": 50,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9h18nGTXd7WKIvMNqCcCKSWFBrfcsm1x76XtncSKiQmB_UAiG",
    "descuento": 1,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 61,
    "stock": 8,
    "disponible": 0,
    "votosup": 48,
    "votosdown": 64
  },
  {
    "id": 1140,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla L",
    "color": "negro",
    "talla": "L",
    "medidas": "20 x 33",
    "precio": 11,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/527B/E2C2/4E0A/7C97/454F/C0A8/28BE/4A44/Trixie_Perro_Coche_I_1290_h.jpg",
    "descuento": 0,
    "categoria": 3,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 16,
    "stock": 0,
    "disponible": 1,
    "votosup": 73,
    "votosdown": 94
  },
  {
    "id": 2556,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "26 x 18",
    "precio": 14,
    "imagen": "https://d2rp9bqx0m7ihv.cloudfront.net/media/1/photos/products/015699/rejilla-ventilacion-para-coches-trixie-perro-coche-1310-h_1_g.jpg",
    "descuento": 1,
    "categoria": 2,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 12,
    "stock": 1,
    "disponible": 0,
    "votosup": 12,
    "votosdown": 9
  },
  {
    "id": 1491,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "27 x 24",
    "precio": 27,
    "imagen": "https://d2rp9bqx0m7ihv.cloudfront.net/media/1/photos/products/015699/rejilla-ventilacion-para-coches-trixie-perro-coche-1310-h_1_g.jpg",
    "descuento": 1,
    "categoria": 4,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 36,
    "stock": 12,
    "disponible": 1,
    "votosup": 20,
    "votosdown": 57
  },
  {
    "id": 1618,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "18 x 37",
    "precio": 2,
    "imagen": "https://http2.mlstatic.com/trixie-perro-pelota-con-cuerda-caucho-natural-7-cm-30-cm-D_NQ_NP_989709-MLM26488658753_122017-F.jpg",
    "descuento": 0,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 26,
    "stock": 4,
    "disponible": 1,
    "votosup": 15,
    "votosdown": 28
  },
  {
    "id": 2996,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "21 x 27",
    "precio": 32,
    "imagen": "https://http2.mlstatic.com/trixie-perro-pelota-con-cuerda-caucho-natural-7-cm-30-cm-D_NQ_NP_989709-MLM26488658753_122017-F.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 60,
    "stock": 14,
    "disponible": 1,
    "votosup": 64,
    "votosdown": 85
  },
  {
    "id": 1145,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "27 x 29",
    "precio": 13,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 0,
    "categoria": 2,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 66,
    "stock": 12,
    "disponible": 0,
    "votosup": 39,
    "votosdown": 31
  },
  {
    "id": 2796,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "21 x 35",
    "precio": 8,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 1,
    "categoria": 2,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 36,
    "stock": 0,
    "disponible": 1,
    "votosup": 12,
    "votosdown": 95
  },
  {
    "id": 2351,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla L",
    "color": "rojo",
    "talla": "L",
    "medidas": "28 x 27",
    "precio": 49,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Cama_I_2807_h.jpg",
    "descuento": 1,
    "categoria": 10,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 50,
    "stock": 12,
    "disponible": 0,
    "votosup": 37,
    "votosdown": 66
  },
  {
    "id": 1149,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "28 x 37",
    "precio": 4,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/527B/E2C2/4E0A/7C97/454F/C0A8/28BE/4A44/Trixie_Perro_Coche_I_1290_h.jpg",
    "descuento": 0,
    "categoria": 4,
    "destacado": 1,
    "favorito": "false",
    "porcentaje": 66,
    "stock": 12,
    "disponible": 1,
    "votosup": 9,
    "votosdown": 83
  },
  {
    "id": 2631,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "21 x 32",
    "precio": 44,
    "imagen": "http://www.mascotas1000.com/WebRoot/StoreLES/Shops/62968959/53AD/8090/6AEC/1A19/F496/C0A8/2BB8/D81E/31862_Perro_Pollo.jpg",
    "descuento": 0,
    "categoria": 7,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 40,
    "stock": 14,
    "disponible": 0,
    "votosup": 42,
    "votosdown": 17
  },
  {
    "id": 1984,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla M",
    "color": "naranja",
    "talla": "M",
    "medidas": "30 x 19",
    "precio": 11,
    "imagen": "https://dasdb9h4gaafx.cloudfront.net/788879/630/e4a8d78be453c9882204ab810d7f1a24.jpg",
    "descuento": 0,
    "categoria": 1,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 15,
    "stock": 9,
    "disponible": 0,
    "votosup": 39,
    "votosdown": 27
  },
  {
    "id": 2641,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla L",
    "color": "negro",
    "talla": "L",
    "medidas": "21 x 24",
    "precio": 1,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9h18nGTXd7WKIvMNqCcCKSWFBrfcsm1x76XtncSKiQmB_UAiG",
    "descuento": 1,
    "categoria": 9,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 64,
    "stock": 7,
    "disponible": 1,
    "votosup": 70,
    "votosdown": 75
  },
  {
    "id": 1655,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "24 x 40",
    "precio": 20,
    "imagen": "http://www.saloncaninoguau.com/wp-content/uploads/2017/02/Trixie_Perro_Viaje_2489_h-300x300.jpg",
    "descuento": 0,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 62,
    "stock": 4,
    "disponible": 1,
    "votosup": 78,
    "votosdown": 19
  },
  {
    "id": 2017,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "24 x 38",
    "precio": 27,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 1,
    "categoria": 8,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 25,
    "stock": 4,
    "disponible": 0,
    "votosup": 31,
    "votosdown": 27
  },
  {
    "id": 2593,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "15 x 32",
    "precio": 3,
    "imagen": "http://www.veterizoniashop.com/5142-home_default/muslitos-de-pollo-y-arroz-light-para-perro-trixie.jpg",
    "descuento": 1,
    "categoria": 7,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 15,
    "stock": 0,
    "disponible": 1,
    "votosup": 47,
    "votosdown": 2
  },
  {
    "id": 1250,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "15 x 23",
    "precio": 3,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Caseta_I_39530_h.jpg",
    "descuento": 1,
    "categoria": 5,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 66,
    "stock": 10,
    "disponible": 0,
    "votosup": 90,
    "votosdown": 15
  },
  {
    "id": 1425,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "17 x 15",
    "precio": 10,
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9h18nGTXd7WKIvMNqCcCKSWFBrfcsm1x76XtncSKiQmB_UAiG",
    "descuento": 1,
    "categoria": 9,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 21,
    "stock": 0,
    "disponible": 0,
    "votosup": 98,
    "votosdown": 29
  },
  {
    "id": 2675,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "25 x 20",
    "precio": 45,
    "imagen": "http://dingopetshop.es/wp-content/uploads/2015/10/Trixie_Perro_Abrigo_dingo-pet-shop-4.jpg",
    "descuento": 0,
    "categoria": 8,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 47,
    "stock": 4,
    "disponible": 0,
    "votosup": 5,
    "votosdown": 96
  },
  {
    "id": 1642,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "18 x 16",
    "precio": 4,
    "imagen": "https://media.animalear.com/media/catalog/product/cache/1/image/400x/9df78eab33525d08d6e5fb8d27136e95/c/h/champu-para-perros-pelo-negro-trixie.jpg",
    "descuento": 1,
    "categoria": 2,
    "destacado": 0,
    "favorito": "false",
    "porcentaje": 39,
    "stock": 12,
    "disponible": 0,
    "votosup": 35,
    "votosdown": 32
  },
  {
    "id": 2440,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "26 x 33",
    "precio": 33,
    "imagen": "http://documentos.trixie.es/Trixie_Perro_Salud_Higiene_I_19470_h.jpg",
    "descuento": 0,
    "categoria": 9,
    "destacado": 0,
    "favorito": "true",
    "porcentaje": 49,
    "stock": 14,
    "disponible": 1,
    "votosup": 91,
    "votosdown": 79
  },
  {
    "id": 1549,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "20 x 15",
    "precio": 38,
    "imagen": "http://www.mascotasreales.es/WebRoot/StoreES/Shops/ea2630/4863/EDAC/CA8C/E790/A2E8/D94C/8776/51BC/Trixie_Perro_Juguete_pelota_denta_fun_menta_perro_lovedogs.jpg",
    "descuento": 1,
    "categoria": 10,
    "destacado": 1,
    "favorito": "true",
    "porcentaje": 33,
    "stock": 7,
    "disponible": 0,
    "votosup": 76,
    "votosdown": 47
  }
];
   return products;
 }

}
