 import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';

@Injectable()
export class RestProvider {

  randomUrl = 'https://randomuser.me/api/?results=25';

    page: string;
  constructor(
    public http: HttpClient,
    private afAuth: AngularFireAuth) {
    console.log('RestProvider Cargado');
  }

  getUsersRandom() {
      return this.http.get(this.randomUrl);
  }

  loginFB(email:string, password:string) {
      return this.afAuth.auth.signInWithEmailAndPassword(email, password)
        .then(user=>Promise.resolve(user))
        .catch(err=>Promise.reject(err))
  }
  catch(e){
    console.log(e);
  }
  initProducts() {
    var products = [
  {
    "id": 2341,
    "nombre": "Silla",
    "descripcion": "Es una Silla de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "19 x 34",
    "precio": 17,
    "imagen": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen1": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen3": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 26,
    "stock": 1,
    "disponible": 1,
    "votosup": 24,
    "votosdown": 99,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2744,
    "nombre": "Cama",
    "descripcion": "Es una Cama de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "30 x 19",
    "precio": 34,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen3": "https://img.interempresas.net/fotos/788082.jpeg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 51,
    "stock": 0,
    "disponible": 1,
    "votosup": 36,
    "votosdown": 96,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2852,
    "nombre": "Mordedor",
    "descripcion": "Es una Mordedor de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "17 x 26",
    "precio": 31,
    "imagen": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen1": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 25,
    "stock": 11,
    "disponible": 0,
    "votosup": 43,
    "votosdown": 57,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 2412,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "23 x 22",
    "precio": 50,
    "imagen": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen1": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 29,
    "stock": 15,
    "disponible": 1,
    "votosup": 3,
    "votosdown": 32,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2606,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "17 x 15",
    "precio": 24,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen3": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 53,
    "stock": 2,
    "disponible": 1,
    "votosup": 92,
    "votosdown": 71,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2022,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "29 x 24",
    "precio": 3,
    "imagen": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen1": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen2": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen3": "https://img.interempresas.net/fotos/788082.jpeg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 34,
    "stock": 7,
    "disponible": 1,
    "votosup": 25,
    "votosdown": 62,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2073,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "27 x 21",
    "precio": 34,
    "imagen": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen1": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen3": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 60,
    "stock": 14,
    "disponible": 1,
    "votosup": 31,
    "votosdown": 49,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1047,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "26 x 30",
    "precio": 50,
    "imagen": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen1": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen2": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen3": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "descuento": 1,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 18,
    "stock": 9,
    "disponible": 1,
    "votosup": 9,
    "votosdown": 63,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1875,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "18 x 39",
    "precio": 17,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen3": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 54,
    "stock": 0,
    "disponible": 1,
    "votosup": 32,
    "votosdown": 100,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 1758,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "16 x 17",
    "precio": 28,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen3": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 57,
    "stock": 4,
    "disponible": 1,
    "votosup": 8,
    "votosdown": 43,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2602,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color rojo y de la talla L",
    "color": "rojo",
    "talla": "L",
    "medidas": "20 x 30",
    "precio": 40,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen3": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 15,
    "stock": 0,
    "disponible": 0,
    "votosup": 37,
    "votosdown": 93,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2154,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "17 x 20",
    "precio": 35,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen3": "https://img.interempresas.net/fotos/788084.jpeg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 16,
    "stock": 3,
    "disponible": 0,
    "votosup": 57,
    "votosdown": 99,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1782,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "15 x 25",
    "precio": 16,
    "imagen": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen2": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen3": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "descuento": 1,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 55,
    "stock": 13,
    "disponible": 0,
    "votosup": 85,
    "votosdown": 38,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2956,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color naranja y de la talla L",
    "color": "naranja",
    "talla": "L",
    "medidas": "18 x 40",
    "precio": 7,
    "imagen": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen1": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 57,
    "stock": 1,
    "disponible": 0,
    "votosup": 67,
    "votosdown": 2,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 1355,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "20 x 24",
    "precio": 50,
    "imagen": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen1": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen3": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 19,
    "stock": 7,
    "disponible": 0,
    "votosup": 49,
    "votosdown": 91,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1774,
    "nombre": "Volador",
    "descripcion": "Es una Volador de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "26 x 26",
    "precio": 15,
    "imagen": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen1": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen2": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 54,
    "stock": 14,
    "disponible": 0,
    "votosup": 44,
    "votosdown": 11,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2871,
    "nombre": "TV",
    "descripcion": "Es una TV de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "15 x 32",
    "precio": 7,
    "imagen": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen2": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen3": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 14,
    "stock": 15,
    "disponible": 1,
    "votosup": 72,
    "votosdown": 2,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2951,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "29 x 19",
    "precio": 1,
    "imagen": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen2": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen3": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 43,
    "stock": 8,
    "disponible": 1,
    "votosup": 19,
    "votosdown": 9,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 1952,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla L",
    "color": "azul",
    "talla": "L",
    "medidas": "19 x 40",
    "precio": 20,
    "imagen": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen1": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 45,
    "stock": 10,
    "disponible": 1,
    "votosup": 48,
    "votosdown": 70,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2304,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla S",
    "color": "rojo",
    "talla": "S",
    "medidas": "28 x 24",
    "precio": 10,
    "imagen": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen1": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen2": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen3": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 59,
    "stock": 10,
    "disponible": 0,
    "votosup": 18,
    "votosdown": 24,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2019,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "21 x 36",
    "precio": 3,
    "imagen": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen1": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 43,
    "stock": 0,
    "disponible": 0,
    "votosup": 65,
    "votosdown": 37,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2667,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "19 x 38",
    "precio": 48,
    "imagen": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen1": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 56,
    "stock": 10,
    "disponible": 0,
    "votosup": 14,
    "votosdown": 21,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2245,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "30 x 21",
    "precio": 17,
    "imagen": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen1": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen3": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 51,
    "stock": 13,
    "disponible": 0,
    "votosup": 3,
    "votosdown": 98,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2502,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "30 x 39",
    "precio": 26,
    "imagen": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen1": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 26,
    "stock": 5,
    "disponible": 0,
    "votosup": 81,
    "votosdown": 5,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1346,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "27 x 24",
    "precio": 43,
    "imagen": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen1": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen2": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen3": "https://img.interempresas.net/fotos/788084.jpeg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 25,
    "stock": 1,
    "disponible": 0,
    "votosup": 14,
    "votosdown": 26,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2477,
    "nombre": "Silla",
    "descripcion": "Es una Silla de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "22 x 20",
    "precio": 49,
    "imagen": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen1": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen2": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen3": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 28,
    "stock": 6,
    "disponible": 1,
    "votosup": 5,
    "votosdown": 88,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 1398,
    "nombre": "Cama",
    "descripcion": "Es una Cama de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "30 x 36",
    "precio": 12,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen3": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 59,
    "stock": 1,
    "disponible": 0,
    "votosup": 41,
    "votosdown": 89,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1694,
    "nombre": "Mordedor",
    "descripcion": "Es una Mordedor de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "24 x 25",
    "precio": 15,
    "imagen": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen1": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen2": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen3": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 23,
    "stock": 3,
    "disponible": 0,
    "votosup": 82,
    "votosdown": 38,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2930,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla M",
    "color": "amarillo",
    "talla": "M",
    "medidas": "16 x 35",
    "precio": 37,
    "imagen": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen1": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 22,
    "stock": 11,
    "disponible": 1,
    "votosup": 40,
    "votosdown": 58,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1327,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla L",
    "color": "azul",
    "talla": "L",
    "medidas": "16 x 22",
    "precio": 36,
    "imagen": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen1": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen2": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 49,
    "stock": 10,
    "disponible": 0,
    "votosup": 67,
    "votosdown": 23,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2494,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "15 x 34",
    "precio": 6,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 17,
    "stock": 15,
    "disponible": 0,
    "votosup": 85,
    "votosdown": 85,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 2400,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "28 x 16",
    "precio": 47,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 36,
    "stock": 11,
    "disponible": 1,
    "votosup": 8,
    "votosdown": 15,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1805,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color rojo y de la talla XS",
    "color": "rojo",
    "talla": "XS",
    "medidas": "24 x 20",
    "precio": 7,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_03_16/58ca8e06c5126_1070x800.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 33,
    "stock": 3,
    "disponible": 0,
    "votosup": 13,
    "votosdown": 51,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2682,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "23 x 33",
    "precio": 18,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 25,
    "stock": 8,
    "disponible": 0,
    "votosup": 11,
    "votosdown": 24,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1873,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla M",
    "color": "amarillo",
    "talla": "M",
    "medidas": "25 x 16",
    "precio": 23,
    "imagen": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 62,
    "stock": 9,
    "disponible": 1,
    "votosup": 72,
    "votosdown": 80,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2998,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color naranja y de la talla L",
    "color": "naranja",
    "talla": "L",
    "medidas": "19 x 32",
    "precio": 29,
    "imagen": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen1": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 61,
    "stock": 2,
    "disponible": 1,
    "votosup": 40,
    "votosdown": 78,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2163,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "21 x 17",
    "precio": 42,
    "imagen": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen1": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 37,
    "stock": 11,
    "disponible": 1,
    "votosup": 90,
    "votosdown": 98,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2757,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "21 x 33",
    "precio": 5,
    "imagen": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen1": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 22,
    "stock": 5,
    "disponible": 0,
    "votosup": 37,
    "votosdown": 93,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2368,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "27 x 40",
    "precio": 40,
    "imagen": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen2": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 69,
    "stock": 2,
    "disponible": 0,
    "votosup": 44,
    "votosdown": 96,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2555,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "23 x 17",
    "precio": 33,
    "imagen": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen2": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen3": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 46,
    "stock": 9,
    "disponible": 0,
    "votosup": 95,
    "votosdown": 35,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1964,
    "nombre": "Volador",
    "descripcion": "Es una Volador de color azul y de la talla XS",
    "color": "azul",
    "talla": "XS",
    "medidas": "21 x 17",
    "precio": 41,
    "imagen": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen1": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen2": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen3": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 19,
    "stock": 12,
    "disponible": 1,
    "votosup": 96,
    "votosdown": 1,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1614,
    "nombre": "TV",
    "descripcion": "Es una TV de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "21 x 22",
    "precio": 11,
    "imagen": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen1": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen2": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 40,
    "stock": 7,
    "disponible": 0,
    "votosup": 71,
    "votosdown": 27,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2989,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "28 x 35",
    "precio": 47,
    "imagen": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen1": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "descuento": 1,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 30,
    "stock": 5,
    "disponible": 0,
    "votosup": 97,
    "votosdown": 53,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 1396,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "29 x 22",
    "precio": 31,
    "imagen": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen1": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "descuento": 1,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 52,
    "stock": 15,
    "disponible": 1,
    "votosup": 91,
    "votosdown": 29,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2395,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "22 x 39",
    "precio": 14,
    "imagen": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen1": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 18,
    "stock": 11,
    "disponible": 0,
    "votosup": 78,
    "votosdown": 82,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1693,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "23 x 33",
    "precio": 30,
    "imagen": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen1": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 22,
    "stock": 2,
    "disponible": 1,
    "votosup": 89,
    "votosdown": 36,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2561,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "28 x 21",
    "precio": 33,
    "imagen": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen1": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 15,
    "stock": 5,
    "disponible": 0,
    "votosup": 63,
    "votosdown": 27,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2837,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "25 x 28",
    "precio": 50,
    "imagen": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen1": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen3": "https://img.interempresas.net/fotos/788084.jpeg",
    "descuento": 1,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 53,
    "stock": 8,
    "disponible": 1,
    "votosup": 66,
    "votosdown": 39,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2326,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color negro y de la talla XS",
    "color": "negro",
    "talla": "XS",
    "medidas": "27 x 19",
    "precio": 34,
    "imagen": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen1": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen2": "https://i.ebayimg.com/images/g/MbEAAOSwbiFZXwOb/s-l300.jpg",
    "imagen3": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 15,
    "stock": 11,
    "disponible": 1,
    "votosup": 31,
    "votosdown": 77,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2938,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "18 x 40",
    "precio": 46,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen3": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 68,
    "stock": 10,
    "disponible": 0,
    "votosup": 16,
    "votosdown": 82,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2680,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla M",
    "color": "rojo",
    "talla": "M",
    "medidas": "15 x 29",
    "precio": 50,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201610/26/00149512001089____3__640x640.jpg",
    "imagen3": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 67,
    "stock": 15,
    "disponible": 1,
    "votosup": 94,
    "votosdown": 91,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2901,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla L",
    "color": "negro",
    "talla": "L",
    "medidas": "28 x 25",
    "precio": 11,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 10,
    "stock": 3,
    "disponible": 1,
    "votosup": 44,
    "votosdown": 6,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2403,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color amarillo y de la talla S",
    "color": "amarillo",
    "talla": "S",
    "medidas": "29 x 15",
    "precio": 14,
    "imagen": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 63,
    "stock": 12,
    "disponible": 1,
    "votosup": 56,
    "votosdown": 31,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2790,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color naranja y de la talla XL",
    "color": "naranja",
    "talla": "XL",
    "medidas": "30 x 18",
    "precio": 27,
    "imagen": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen1": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788082.jpeg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 69,
    "stock": 14,
    "disponible": 0,
    "votosup": 93,
    "votosdown": 86,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 1732,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "20 x 32",
    "precio": 2,
    "imagen": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen2": "https://images-na.ssl-images-amazon.com/images/I/71LiCXNxKNL._SY355_.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 32,
    "stock": 6,
    "disponible": 0,
    "votosup": 72,
    "votosdown": 19,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2804,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "22 x 22",
    "precio": 32,
    "imagen": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen1": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen2": "https://http2.mlstatic.com/platillo-trixie-con-accesorios-para-perro-D_NQ_NP_662780-MCO25815789925_072017-F.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 42,
    "stock": 9,
    "disponible": 0,
    "votosup": 46,
    "votosdown": 87,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2695,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "25 x 32",
    "precio": 13,
    "imagen": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen1": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen2": "https://www.terranovacnc.com/wp-content/uploads/2017/11/trixie-divisorio-metalico-3-elementos-para-coche-para-perros.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 27,
    "stock": 10,
    "disponible": 1,
    "votosup": 32,
    "votosdown": 94,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2252,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla M",
    "color": "azul",
    "talla": "M",
    "medidas": "30 x 34",
    "precio": 8,
    "imagen": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen1": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen2": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "imagen3": "http://piensosjuan.es/606-home_default/trixie-puerta-gatera-4-posiciones-con-tunel-blanco.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 43,
    "stock": 11,
    "disponible": 1,
    "votosup": 90,
    "votosdown": 24,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1711,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color rojo y de la talla L",
    "color": "rojo",
    "talla": "L",
    "medidas": "15 x 39",
    "precio": 49,
    "imagen": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen2": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen3": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 30,
    "stock": 6,
    "disponible": 1,
    "votosup": 4,
    "votosdown": 75,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2074,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla S",
    "color": "negro",
    "talla": "S",
    "medidas": "23 x 30",
    "precio": 4,
    "imagen": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen2": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen3": "https://img.interempresas.net/fotos/788084.jpeg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 62,
    "stock": 9,
    "disponible": 0,
    "votosup": 67,
    "votosdown": 7,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 2745,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "19 x 20",
    "precio": 44,
    "imagen": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen1": "http://documentos.trixie.es/Trixie_Roedores_Accesorios_61513_h.jpg",
    "imagen2": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen3": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 16,
    "stock": 8,
    "disponible": 1,
    "votosup": 78,
    "votosdown": 37,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 1203,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color naranja y de la talla M",
    "color": "naranja",
    "talla": "M",
    "medidas": "29 x 21",
    "precio": 11,
    "imagen": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen1": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen2": "https://img.interempresas.net/fotos/788084.jpeg",
    "imagen3": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 58,
    "stock": 9,
    "disponible": 0,
    "votosup": 28,
    "votosdown": 63,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1386,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color negro y de la talla L",
    "color": "negro",
    "talla": "L",
    "medidas": "23 x 21",
    "precio": 1,
    "imagen": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen1": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen2": "https://http2.mlstatic.com/rascador-casa-cama-gatos-juguete-accesorios-giuseppe-trixie-D_NQ_NP_695121-MLM25537005909_042017-F.jpg",
    "imagen3": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "descuento": 0,
    "categoria": "Pajaros",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 53,
    "stock": 11,
    "disponible": 1,
    "votosup": 1,
    "votosdown": 64,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2819,
    "nombre": "Manta",
    "descripcion": "Es una Manta de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "24 x 38",
    "precio": 20,
    "imagen": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen1": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen2": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 46,
    "stock": 13,
    "disponible": 0,
    "votosup": 43,
    "votosdown": 59,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2075,
    "nombre": "Ara�ador",
    "descripcion": "Es una Ara�ador de color amarillo y de la talla XL",
    "color": "amarillo",
    "talla": "XL",
    "medidas": "30 x 38",
    "precio": 27,
    "imagen": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen1": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen2": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen3": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 25,
    "stock": 6,
    "disponible": 0,
    "votosup": 45,
    "votosdown": 82,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 1895,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color azul y de la talla S",
    "color": "azul",
    "talla": "S",
    "medidas": "15 x 31",
    "precio": 3,
    "imagen": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen1": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen2": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen3": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "descuento": 1,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 63,
    "stock": 7,
    "disponible": 1,
    "votosup": 6,
    "votosdown": 30,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2570,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color azul y de la talla XL",
    "color": "azul",
    "talla": "XL",
    "medidas": "25 x 28",
    "precio": 3,
    "imagen": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen1": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen2": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 0,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 1,
    "porcentaje": 30,
    "stock": 2,
    "disponible": 1,
    "votosup": 65,
    "votosdown": 98,
    "novedad": 0,
    "carrito": 0
  },
  {
    "id": 2706,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color rojo y de la talla XL",
    "color": "rojo",
    "talla": "XL",
    "medidas": "25 x 35",
    "precio": 10,
    "imagen": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen1": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "imagen2": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "imagen3": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "descuento": 1,
    "categoria": "Pajaros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 64,
    "stock": 8,
    "disponible": 0,
    "votosup": 9,
    "votosdown": 54,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 2817,
    "nombre": "Juguete",
    "descripcion": "Es una Juguete de color negro y de la talla M",
    "color": "negro",
    "talla": "M",
    "medidas": "18 x 21",
    "precio": 45,
    "imagen": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen1": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "descuento": 0,
    "categoria": "Elefantes",
    "destacado": 0,
    "favorito": 0,
    "porcentaje": 67,
    "stock": 8,
    "disponible": 1,
    "votosup": 70,
    "votosdown": 45,
    "novedad": 0,
    "carrito": 1
  },
  {
    "id": 2586,
    "nombre": "Mesa",
    "descripcion": "Es una Mesa de color amarillo y de la talla L",
    "color": "amarillo",
    "talla": "L",
    "medidas": "23 x 31",
    "precio": 4,
    "imagen": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen1": "http://www.oasisgarden.net/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/b/e/bebedero_1_2.jpg",
    "imagen2": "https://uploads.zoobio.de/resize/products/2017_07_12/5965f5a2a5b6d_130x180.jpg",
    "imagen3": "https://petplaza.pe/wp-content/uploads/2014/10/trixie_juguetes_higiene_limpieza_correa_tiro_arnes_dental_cuerda_platos_bowl_mascota_perro_gato_juego_petplaza_goodie_bag_bolso_porta_premios_recompensa2-465x528.jpg",
    "descuento": 1,
    "categoria": "Hurones",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 14,
    "stock": 3,
    "disponible": 0,
    "votosup": 29,
    "votosdown": 17,
    "novedad": 1,
    "carrito": 0
  },
  {
    "id": 1460,
    "nombre": "Puerta",
    "descripcion": "Es una Puerta de color naranja y de la talla S",
    "color": "naranja",
    "talla": "S",
    "medidas": "28 x 25",
    "precio": 33,
    "imagen": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen1": "https://kiwoko.a.ssl.fastly.net/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/4/0/4011905607351.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "http://nutrifauna2000.es/img/servicios/accesorios-complementos.jpg",
    "descuento": 0,
    "categoria": "Perros",
    "destacado": 0,
    "favorito": 1,
    "porcentaje": 60,
    "stock": 12,
    "disponible": 1,
    "votosup": 100,
    "votosdown": 38,
    "novedad": 1,
    "carrito": 1
  },
  {
    "id": 2754,
    "nombre": "Colchon",
    "descripcion": "Es una Colchon de color negro y de la talla XL",
    "color": "negro",
    "talla": "XL",
    "medidas": "16 x 16",
    "precio": 38,
    "imagen": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen1": "https://media.feelcats.com/media/catalog/product/cache/1/image/900x900/9df78eab33525d08d6e5fb8d27136e95/c/o/comedero-para-gatos-automatico-tx4-4x500-ml-gris-y-negro-trixie-feelcats-cb0050.jpg",
    "imagen2": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "imagen3": "http://www.petydog.es/intranet/software/imagenes/articulos/151_____hueso33542.jpg",
    "descuento": 1,
    "categoria": "Gatos",
    "destacado": 1,
    "favorito": 0,
    "porcentaje": 58,
    "stock": 11,
    "disponible": 0,
    "votosup": 22,
    "votosdown": 55,
    "novedad": 1,
    "carrito": 0
  }
];
   return products;
 }

}
